export const estacoesAuto = `
    TODAS
    ABROLHOS
    ACARAU
    AFONSO CLAUDIO
    AGUA BOA
    AGUA CLARA
    AGUAS EMENDADAS
    AGUAS VERMELHAS
    AIMORES
    ALEGRE
    ALEGRETE
    ALFREDO CHAVES
    ALMAS
    ALMENARA
    ALTA FLORESTA
    ALTAMIRA
    ALTO ARAGUAIA
    ALTO PARAISO DE GOIAS
    ALTO PARNAIBA
    ALTO TAQUARI
    ALVORADA DO GURGUEIA
    AMAMBAI
    AMARGOSA
    ANGICAL DO PIAUI
    ANGRA DOS REIS
    APIACAS
    APODI
    APUI
    AQUIDAUANA
    ARACAJU
    ARACUAI
    ARAGARCAS
    ARAGUACU
    ARAGUAINA
    ARAGUATINS
    ARAPIRACA
    ARARANGUA
    ARAXA
    ARCO VERDE
    AREIA
    ARIQUEMES
    ARIRANHA
    ARRAIAL DO CABO
    AUTAZES
    AVARE
    BACABAL
    BAGE
    BAIXA GRANDE DO RIBEIRO
    BALSAS
    BAMBUI
    BARBACENA
    BARBALHA
    BARCELOS
    BARRA
    BARRA BONITA
    BARRA DO CORDA
    BARRA DO TURVO
    BARREIRAS
    BARRETOS
    BARUERI
    BATAGUASSU
    BAURU
    BEBEDOURO
    BELEM
    BELMONTE
    BELO HORIZONTE (PAMPULHA)
    BELO HORIZONTE - CERCADINHO
    BENTO GONCALVES
    BERTIOGA
    BOA VISTA
    BOCA DO ACRE
    BOM JARDIM DA SERRA - MORRO DA IGREJA
    BOM JESUS DA LAPA
    BOM JESUS DO PIAUI
    BRAGANCA
    BRAGANCA PAULISTA
    BRASILIA
    BRASNORTE (NOVO MUNDO)
    BRAZLANDIA
    BREJO GRANDE
    BREVES
    BRUMADO
    BURITICUPU
    BURITIRAMA
    BURITIS
    CABACEIRAS
    CABROBO
    CACADOR
    CACAPAVA DO SUL
    CACHOEIRA PAULISTA
    CACOAL
    CAIAPONIA
    CAICO
    CALCANHAR
    CALDAS
    CAMAQUA
    CAMARATUBA
    CAMBARA DO SUL
    CAMBUCI
    CAMETA
    CAMPINA DA LAGOA
    CAMPINA GRANDE
    CAMPINA VERDE
    CAMPO BOM
    CAMPO GRANDE
    CAMPO MAIOR
    CAMPO NOVO DOS PARECIS
    CAMPO VERDE
    CAMPOS DO JORDAO
    CAMPOS DOS GOYTACAZES
    CAMPOS DOS GOYTACAZES - SAO TOME
    CAMPOS LINDOS
    CAMPOS NOVOS
    CAMPOS SALES
    CANELA
    CANGUCU
    CANTO DO BURITI
    CAPAO DO LEAO (PELOTAS)
    CAPELINHA
    CAPITAO POCO
    CARACOL
    CARATINGA
    CARAVELAS
    CARLINDA
    CARMO
    CAROLINA
    CARUARU
    CASA BRANCA
    CASSILANDIA
    CASTANHAL
    CASTELO DO PIAUI
    CASTRO
    CATALAO
    CAXIAS
    CHAPADA GAUCHA
    CHAPADAO DO SUL
    CHAPADINHA
    CHAPECO
    CIDADE GAUCHA
    CLEVELANDIA
    COARI
    COLINAS
    COLINAS DO TOCANTINS
    COLOMBO
    COMODORO
    CONCEICAO DAS ALAGOAS
    CONCEICAO DO ARAGUAIA
    CONDE
    CORONEL PACHECO
    CORRENTE
    CORRENTINA
    CORUMBA
    CORURIPE
    COSTA RICA
    COTRIGUACU
    COXIM
    CRATEUS
    CRISTALINA
    CRISTALINA (FAZENDA SANTA MONICA)
    CRUZ ALTA
    CRUZ DAS ALMAS
    CRUZEIRO DO SUL
    CUIABA
    CURACA
    CURITIBA
    CURITIBANOS
    CURVELO
    DELFINO
    DIAMANTE DO NORTE
    DIAMANTINA
    DIANOPOLIS
    DIONISIO CERQUEIRA
    DIVINOPOLIS
    DOIS VIZINHOS
    DOM ELISEU
    DOM PEDRITO
    DORES DO INDAIA
    DOURADOS
    DRACENA
    DUQUE DE CAXIAS - XEREM
    ECOPORANGA
    EDEIA
    EIRUNEPE
    ENCRUZILHADA DO SUL
    EPITACIOLANDIA
    ERECHIM
    ESPINOSA
    ESTREITO
    EUCLIDES DA CUNHA
    FAROL de SANTANA
    FEIJO
    FEIRA DE SANTANA
    FLORESTA
    FLORESTAL
    FLORIANO
    FLORIANOPOLIS
    FORMIGA
    FORMOSA DO RIO PRETO
    FORMOSO DO ARAGUAIA
    FORTALEZA
    FOZ DO IGUACU
    FRANCA
    FREDERICO WESTPHALEN
    GAMA (PONTE ALTA)
    GARANHUNS
    GAUCHA DO NORTE
    GENERAL CARNEIRO
    GILBUES
    GOIANESIA
    GOIANIA
    GOIAS
    GOIOERE
    GOVERNADOR VALADARES
    GRAJAU
    GUANAMBI
    GUANHAES
    GUARAMIRANGA
    GUARANTA DO NORTE
    GUARDA-MOR
    GUIRATINGA
    GURUPI
    HUMAITA
    IBIMIRIM
    IBIRITE (ROLA MOCA)
    IBIRUBA
    IBITINGA
    IBOTIRAMA
    ICARAIMA
    IGUAPE
    IGUATU
    ILHEUS
    IMPERATRIZ
    INACIO MARTINS
    INDAIAL
    IPANGUACU
    IPIAU
    IPORA
    IRECE
    ITABAIANA
    ITABAIANINHA
    ITABERABA
    ITACOATIARA
    ITAITUBA
    ITAJAI
    ITAMARAJU
    ITAOBIM
    ITAPACI
    ITAPETINGA
    ITAPEVA
    ITAPIPOCA
    ITAPIRA
    ITAPOA
    ITAPORANGA
    ITAQUIRAI
    ITAUBAL
    ITIQUIRA
    ITIRUCU
    ITUIUTABA
    ITUMBIARA
    ITUPORANGA
    ITUVERAVA
    IVAI
    IVINHEMA
    JACOBINA
    JAGUARAO
    JAGUARIBE
    JAGUARUANA
    JALES
    JANUARIA
    JAPIRA
    JARDIM
    JATAI
    JEREMOABO
    JOACABA
    JOAO PESSOA
    JOAO PINHEIRO
    JOAQUIM TAVORA
    JOSE BONIFACIO
    JUARA
    JUINA
    JUIZ DE FORA
    JUTI
    LABREA
    LAGES
    LAGOA DA CONFUSAO
    LAGOA VERMELHA
    LARANJEIRAS DO SUL
    LENCOIS
    LINHARES
    LINS
    LUIZ EDUARDO MAGALHAES
    LUZIANIA
    Laguna  - Farol de Santa Marta
    MACAE
    MACAJUBA
    MACAPA
    MACAU
    MACEIO
    MACHADO
    MAJOR VIEIRA
    MAL
    MANACAPURU
    MANAUS
    MANHUACU
    MANICORE
    MANTENA
    MARABA
    MARACAJU
    MARAU
    MARECHAL THAUMATURGO
    MARIA DA FE
    MARIANOPOLIS DO TO
    MARILANDIA
    MARILIA
    MARINGA
    MATEIROS
    MAUES
    MEDICILANDIA
    MINA DO PALITO
    MINEIROS
    MIRANDA
    MOCAMBINHO
    MONTALVANIA
    MONTE ALEGRE
    MONTE ALEGRE DE GOIAS
    MONTE VERDE
    MONTEIRO
    MONTES CLAROS
    MORADA NOVA
    MORRETES
    MORRINHOS
    MOSSORO
    MOSTARDAS
    MURIAE
    NATAL
    NHUMIRIM
    NITEROI
    NOSSA SENHORA DA GLORIA
    NOVA FATIMA
    NOVA FRIBURGO - SALINAS
    NOVA MARINGA
    NOVA PORTEIRINHA (JANAUBA)
    NOVA TEBAS
    NOVA UBIRATA
    NOVO ARIPUANA
    NOVO HORIZONTE
    NOVO REPARTIMENTO
    OBIDOS
    OEIRAS
    OIAPOQUE
    OLIVEIRA
    OURICURI
    OURINHOS
    OURO BRANCO
    PACAJA
    PALMARES
    PALMAS
    PALMEIRA DAS MISSOES
    PALMEIRA DOS INDIOS
    PAO DE ACUCAR
    PARACATU
    PARAGOMINAS
    PARANA
    PARANAIBA
    PARANAPOEMA
    PARANATINGA
    PARANOA (COOPA-DF)
    PARATY
    PARAUNA
    PARINTINS
    PARNAIBA
    PARQUE ESTADUAL CHANDLESS
    PASSA QUATRO
    PASSO FUNDO
    PASSOS
    PATOS
    PATOS DE MINAS
    PATROCINIO
    PAULISTANA
    PEDRO AFONSO
    PEIXE
    PETROLINA
    PIATA
    PICO DO COUTO
    PICOS
    PIRACICABA
    PIRANHAS
    PIRAPORA
    PIRES DO RIO
    PIRIPIRI
    PIUM
    PLACAS
    PLANALTO
    POCO VERDE
    POMPEU
    PONTA PORA
    PONTES E LACERDA
    PORANGATU
    PORTO ALEGRE - JARDIM BOTANICO
    PORTO ALEGRE- BELEM NOVO
    PORTO DE MOZ
    PORTO ESTRELA
    PORTO GRANDE
    PORTO MURTINHO
    PORTO SEGURO
    PORTO VELHO
    PORTO WALTER
    POSSE
    PRADOPOLIS
    PREGUICAS
    PRESIDENTE FIGUEIREDO
    PRESIDENTE KENNEDY
    PRESIDENTE PRUDENTE
    PRIMAVERA DO LESTE
    Paty do Alferes - Avelar
    QUARAI
    QUEIMADAS
    QUERENCIA
    QUIXADA
    QUIXERAMOBIM
    RANCHARIA
    RANCHO QUEIMADO
    REDENCAO
    REGISTRO
    REMANSO
    RESENDE
    RIBEIRA DO AMPARO
    RIO BRANCO
    RIO BRILHANTE
    RIO CLARO
    RIO DE JANEIRO - FORTE DE COPACABANA
    RIO DE JANEIRO - JACAREPAGUA
    RIO DE JANEIRO - VILA MILITAR
    RIO DE JANEIRO-MARAMBAIA
    RIO DO CAMPO
    RIO GRANDE
    RIO NEGRINHO
    RIO PARDO
    RIO PARDO DE MINAS
    RIO SONO
    RIO URUBU
    RIO VERDE
    RONDON DO PARA
    RONDONOPOLIS
    ROSARIO OESTE
    S
    S
    SACRAMENTO
    SALGUEIRO
    SALINAS
    SALINOPOLIS
    SALTO DO CEU
    SALVADOR
    SALVADOR (RADIO FAROL)
    SANTA CRUZ
    SANTA FE DO ARAGUAIA
    SANTA MARIA
    SANTA MARIA DAS BARREIRAS
    SANTA MARIA MADALENA
    SANTA RITA DE CASSIA
    SANTA ROSA
    SANTA ROSA DO TOCANTINS
    SANTA TERESA
    SANTANA DO ARAGUAIA
    SANTANA DO LIVRAMENTO
    SANTAREM
    SANTIAGO
    SANTO ANTONIO DO LESTE
    SANTO AUGUSTO
    SAO BORJA
    SAO CARLOS
    SAO FELIX  DO ARAGUAIA
    SAO FELIX DO XINGU
    SAO GABRIEL
    SAO GABRIEL DO OESTE
    SAO GONCALO
    SAO JOAO DEL REI
    SAO JOAO DO PIAUI
    SAO JOAQUIM
    SAO JOSE DO XINGU
    SAO JOSE DOS AUSENTES
    SAO LUIS
    SAO LUIS DO QUITUNDE
    SAO LUIZ DO PARAITINGA
    SAO LUIZ GONZAGA
    SAO MATEUS
    SAO MATEUS DO SUL
    SAO MIGUEL ARCANJO
    SAO MIGUEL DO ARAGUAIA
    SAO MIGUEL DO OESTE
    SAO PAULO - INTERLAGOS
    SAO PAULO - MIRANTE
    SAO RAIMUNDO NONATO
    SAO ROMAO
    SAO SEBASTIAO DO PARAISO
    SAO SIMAO
    SAO SIMAO
    SAO VICENTE DO SUL
    SAPEZAL
    SAQUAREMA - SAMPAIO CORREIA
    SENHOR DO BONFIM
    SERAFINA CORREA
    SEROPEDICA-ECOLOGIA AGRICOLA
    SERRA DOS AIMORES
    SERRA DOS CARAJAS
    SERRA NOVA DOURADA
    SERRA TALHADA
    SERRINHA
    SETE LAGOAS
    SETE QUEDAS
    SIDROLANDIA
    SILVA JARDIM
    SILVANIA
    SINOP
    SOBRAL
    SOLEDADE
    SONORA
    SOROCABA
    SORRISO
    SOURE
    SURUBIM
    Santa Vitoria do Palmar - Barra do Chui
    TANGARA DA SERRA
    TAUA
    TAUBATE
    TEOFILO OTONI
    TERESINA
    TERESOPOLIS-PARQUE NACIONAL
    TEUTONIA
    TIANGUA
    TIMOTEO
    TOME ACU
    TORRES
    TRAMANDAI
    TRES LAGOAS
    TRES MARIAS
    TRES RIOS
    TUCUMA
    TUCURUI
    TUPA
    TUPANCIRETA
    TURIACU
    UBERABA
    UBERLANDIA
    UNA
    UNAI
    URUCARA
    URUCUI
    URUGUAIANA
    URUSSANGA
    VACARIA
    VALENCA
    VALENCA
    VALENCA DO PIAUI
    VALPARAISO
    VARGINHA
    VENDA NOVA DO IMIGRANTE
    VENTANIA
    VICOSA
    VILA BELA DA SANTISSIMA TRINDADE
    VILA VELHA
    VILHENA
    VITORIA
    VITORIA DA CONQUISTA
    XANXERE
    XINGUARA
    ZE DOCA`.split(' ').join('').split('\n').filter(Boolean);


export const estacoesConv = `
TODAS
AGUA BRANCA
ALTAMIRA
ALTO DA BOA VISTA
APODI
ARACUAI
ARAGARCAS
ARAGUAINA
ARAXA
ARCO VERDE
AREIA
ARINOS
BACABAL
BAGE
BALSAS
BARRA
BARRA DO CORDA
BARREIRAS
BELEM
BELO HORIZONTE
BELTERRA
BENJAMIN CONSTANT
BOA VISTA
BOM JESUS
BOM JESUS DA LAPA
BOM JESUS DO PIAUI
BRASILIA
BREVES
C
CABROBO
CAMETA
CAMPINA GRANDE
CAMPOS
CANARANA
CAPARAO
CARACARAI
CARATINGA
CARAVELAS
CARBONITA
CAROLINA
CATALAO
CAXIAS DO SUL
CEARA MIRIM
CHAPADINHA
CIPO
CODAJAS
COLINAS
CONCEICAO DO ARAGUAIA
CORDEIRO
CORRENTINA
CRUZ ALTA
CRUZ DAS ALMAS
CUIABA
DIAMANTINO
FLORIANO
FONTE BOA
FORMOSA
FORMOSO
FORTALEZA
FRANCA
GOIANIA
GUARATINGA
IGUABA GRANDE
IMPERATRIZ
IPAMERI
IRATI
ITACOATIARA
ITAITUBA
ITAMARANDIBA
ITAPERUNA
JANUARIA
JATAI
JOAO PESSOA
JUIZ DE FORA
JURAMENTO
LABREA
LAGOA VERMELHA
LAVRAS
LENCOIS
LONDRINA
LUZILANDIA(LAG
MACAPA
MANAUS
MARABA
MARINGA
MONTE ALEGRE
MONTEIRO
MONTES CLAROS
MORADA NOVA
MORRO DO CHAPEU
MUNIZ FREIRE
NATAL
NOVA XAV
OURICURI
PADRE RICARDO REMETTER
PALMAS
PALMEIRA DOS INDIOS
PAO DE ACUCAR
PARANAIBA
PASSA QUATRO
PASSO FUNDO
PATOS
PAULISTANA
PEDRA AZUL
PEDRO AFONSO
PEIXE
PELOTAS
PETROLINA
PICOS
PIRENOPOLIS
PIRIPIRI
PORTO ALEGRE
PORTO DE MOZ
PORTO DE PEDRAS
PORTO NACIONAL
POSSE
PROPRIA
QUIXERAMOBIM
RESENDE
RIO VERDE
SALINAS
SALVADOR (ONDINA)
SANTA MARIA
SANTA MARIA MADALENA
SANTA VITORIA DO PALMAR
SAO CARLOS
SAO GABRIEL DA CACHOEIRA(UAUPES)
SAO GONCALO
SAO JOAO DO PIAUI
SAO LOURENCO
SAO LUIS
SAO PAULO(MIR
SAO SIMAO
SAO VICENTE
SERIDO (CAICO)
SOROCABA
SURUBIM
TAGUATINGA
TARAUACA
TEFE
TERESINA
TERESOPOLIS
TRACUATEUA
TUCURUI
TURIACU
UNAI
VITORIA
VITORIA DA CONQUISTA
ZE DOCA
`.split(' ').join('').split('\n').filter(Boolean);


